AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:  # Instance Name should have better meaning
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro  # CPU performance issue
      ImageId: 'ami-0abcdef1234567890'
      KeyName: MyKeyPair  # naming convention
      SecurityGroups:
        - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead # should not be public available if not required

Outputs:
  InstancePublicIp:
    Description: 'The public IP of the EC2 instance'
    Value: 
      !GetAtt
        - MyEC2Instance
        - PublicIp

